# What is NumPy?

🔷 **NumPy** is a powerful Python library used for numerical computations. It stands for **Numerical Python** and provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.

### Why is NumPy Important for Data Science (DS) and AIML?

🔶 **`NumPy is Fast`**: NumPy's core is written in **C**, making it much faster than Python lists, especially for handling large datasets used in **DS** and **AIML**. It significantly reduces processing time when working with millions or billions of data points.

🔶 **`Memory Efficiency`**: NumPy arrays are stored **contiguously in memory**, which improves performance by reducing memory overhead compared to Python lists that are scattered in memory.

🔶 **`NumPy is Convenient`**: It provides a wide range of tools for **data manipulation** (reshaping, slicing, aggregating), making it extremely **convenient** for handling complex mathematical operations, without writing lengthy or complicated code.

🔶 **`Vectorized Operations`**: NumPy supports **vectorized operations**, meaning operations on arrays can be done without using explicit loops, speeding up computations and reducing code complexity.

🔶 **`Mathematical and Statistical Functions`**: It includes an extensive set of mathematical functions (linear algebra, statistics, etc.), crucial for building and optimizing **machine learning models**.

### Key Features of NumPy

🟢 **Multidimensional Arrays**: Supports creating arrays of any dimension (1D, 2D, 3D, etc.), making it suitable for handling structured data like images, sound, or tabular data.

🟢 **Broadcasting**: NumPy allows operations between arrays of different shapes, known as **broadcasting**, which simplifies the code and enhances performance.

🟢 **Integration with Other Libraries**: Most popular data science and AIML libraries like **Pandas**, **TensorFlow**, and **Scikit-learn** are built on top of or heavily rely on NumPy.

🟢 **Interfacing with C/C++ and Fortran**: NumPy can integrate directly with low-level languages, providing a performance boost and allowing access to advanced computational libraries.

---


# NumPy Array vs Python Lists:

### 1. Memory Efficiency

In [1]:
import numpy as np
import time 
import sys

In [2]:
l = range(1000)
print(sys.getsizeof(1)*len(l))

28000


In [3]:
arr = np.arange(1000)
print(arr.size*arr.itemsize)

8000


<img src="https://www.researchgate.net/publication/344044674/figure/fig10/AS:931300496121865@1599050749620/NumPy-ndarray-vs-Python-list-Van.png" align="center">

### 2. NumPy is Fast

In [4]:
size = 1000000

l1 = range(size)
l2 = range(size)

arr1 = np.arange(size)
arr2 = np.arange(size)

# Python List
start = time.time()
res = [(x+y) for x,y in zip(l1,l2)]
print(f"Python List took: {(time.time()-start)*1000}ms")

# Numpy Array
start = time.time()
res1 = arr1+arr2
print(f"Numpy took: {(time.time()-start)*1000}ms")

Python List took: 70.0063705444336ms
Numpy took: 1.9996166229248047ms


### NumPy is Convinient

In [5]:
arr = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr,"\n")

# Reshaping to a 2D array (converting 1D to 2D)
arr_reshaped = arr.reshape(1, 5)
print("Reshaped 2D Array:\n", arr_reshaped,"\n")

# Creating a 2D array of zeros
zeros_array = np.zeros((3, 3))
print("2D Array of Zeros:\n", zeros_array,"\n")

1D Array: [1 2 3 4 5] 

Reshaped 2D Array:
 [[1 2 3 4 5]] 

2D Array of Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 



- In `NumPy`, we can perform **mathematical operations** across an `entire array` **without writing explicit loops**.

In [6]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

# Adding arrays element-wise
result_add = arr1 + arr2
print("Element-wise Addition:", result_add,"\n")

# Multiplying arrays element-wise
result_mul = arr1 * arr2
print("Element-wise Multiplication:", result_mul,"\n")

# Exponentiation
result_exp = np.exp(arr1)
print("Exponential of each element:", result_exp,"\n")

Element-wise Addition: [ 6  8 10 12] 

Element-wise Multiplication: [ 5 12 21 32] 

Exponential of each element: [ 2.71828183  7.3890561  20.08553692 54.59815003] 

