## 1. Creating Multi-dimentional Array

In [1]:
import numpy as np

# Creating a 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1,"\n")

# Creating a 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2,"\n")


1D Array: [1 2 3 4 5] 

2D Array:
 [[1 2 3]
 [4 5 6]] 



## 2. ndim Property(Number of Dimensions)

In [2]:
print("Number of dimensions of 1D array:", arr1.ndim)
print("Number of dimensions of 2D array:", arr2.ndim,"\n")

Number of dimensions of 1D array: 1
Number of dimensions of 2D array: 2 



## 3. Item Size Property

In [3]:
# Checking item size
print("Item size of 1D array:", arr1.itemsize, "bytes")
print("Item size of 2D array:", arr2.itemsize, "bytes\n")


Item size of 1D array: 8 bytes
Item size of 2D array: 8 bytes



## 4. dtype Property

In [5]:
# Checking data type
print("Data type of 1D array:", arr1.dtype)
print("Data type of 2D array:", arr2.dtype,"\n")

Data type of 1D array: int64
Data type of 2D array: int64 



## 5. Change Data Type of Elements

In [7]:
# Changing data type to float
arr_float = arr1.astype(float)
print("Array with changed data type to float:", arr_float,"\n")

Array with changed data type to float: [1. 2. 3. 4. 5.] 



## 6. Size Property

In [8]:
# Checking size
print("Size of 1D array:", arr1.size)
print("Size of 2D array:", arr2.size,"\n")


Size of 1D array: 5
Size of 2D array: 6 



## 7. Shape Property

In [12]:
# Checking shape
print(arr1,"\n")
print(arr2,"\n")
print("Shape of 1D array:", arr1.shape)
print("Shape of 2D array:", arr2.shape,"\n")

[1 2 3 4 5] 

[[1 2 3]
 [4 5 6]] 

Shape of 1D array: (5,)
Shape of 2D array: (2, 3) 



## 8. zeros() Function (Creating an Array Filled with Zeros)

In [18]:
# Creating a 2D array of zeros
arr_zeros = np.zeros((3, 3))
print("Array of Zeros:\n", arr_zeros,"\n")


Array of Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 



## 9. ones() Function

In [19]:
# Creating a 2D array of ones
arr_ones = np.ones((3, 3))
print("Array of Ones:\n", arr_ones,"\n")


Array of Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 



## 10. arrange() Function [Creating a NumPy Array with a Range of Values]

In [20]:
# Creating a NumPy array with arange
arr_range = np.arange(1, 10)
print("NumPy arange:", arr_range)


NumPy arange: [1 2 3 4 5 6 7 8 9]


## 11. linspace() Function [Creating Evenly Spaced Values in a Range]

In [21]:
# Creating an array with 5 values between 1 and 10
arr_linspace = np.linspace(1, 10, 5)
print("NumPy linspace:", arr_linspace)


NumPy linspace: [ 1.    3.25  5.5   7.75 10.  ]


## 12. reshape() Function

In [23]:
# Reshaping a 1D array to 2D
arr_reshaped = arr_range.reshape(3, 3)
print("Reshaped Array:\n", arr_reshaped)


Reshaped Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


## 13.  ravel() Function (Flattening an Array)

In [24]:
# Flattening a 2D array back to 1D
arr_flattened = arr_reshaped.ravel()
print("Flattened Array:", arr_flattened)


Flattened Array: [1 2 3 4 5 6 7 8 9]


## 14. min(), max() & sum() Function 

In [27]:
print("Minimum value in array:", arr_range.min())
print("Maximum value in array:", arr_range.max())
print("Sum of array elements:", arr_range.sum())


Minimum value in array: 1
Maximum value in array: 9
Sum of array elements: 45


## 15. sqrt() Function (Square Root of Each Element in an Array)

In [28]:
# Finding square root of each element
arr_sqrt = np.sqrt(arr_range)
print("Square root of elements:\n", arr_sqrt)

Square root of elements:
 [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]


## 16. std() Function (Standard Deviation of Array Elements)

In [29]:
# Finding standard deviation
print("Standard Deviation:", arr_range.std())

Standard Deviation: 2.581988897471611


## 17. Array Operations

In [30]:
# Adding two arrays
arr_add = arr_range + arr_ones.ravel()  # Adjusting dimensions
print("Element-wise addition:\n", arr_add)

# Multiplying two arrays
arr_mul = arr_range * arr_ones.ravel()
print("Element-wise multiplication:\n", arr_mul)


Element-wise addition:
 [ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
Element-wise multiplication:
 [1. 2. 3. 4. 5. 6. 7. 8. 9.]


## 18. Matrix Products using dot() Function

In [31]:
# Creating two matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Performing matrix multiplication (dot product)
matrix_product = np.dot(matrix1, matrix2)
print("Matrix Product:\n", matrix_product,"\n\n")


Matrix Product:
 [[19 22]
 [43 50]] 


