<h1 style="color: blueviolet;">1. What is Indexing and Slicing?</h1>

- <span style="background-color: #f0f0f0; color:Tomato; font-weight:500;border-radius:5px;"><em>Indexing</em>:</span> Accessing individual elements of an array using their **index positions**.
- <span style="background-color: #f0f0f0; color:Tomato; font-weight:500;border-radius:5px;"><em>Slicing</em>:</span> Accessing a subset of an array by specifying a **range** of indices.

In [1]:
# In Lists:
l1 = [6,7,8]
print(l1[0:2])
print(l1[-1],"\n")

[6, 7]
8 



In [2]:
# Similarly in NumPy Array:
import numpy as np
arr = np.array([6,7,8])
print(arr[0:2])
print(arr[-1],"\n")

[6 7]
8 



- <h4>In MultiDimentional Array</h4>

In [3]:
arr1 = np.array([[6,7,8],[1,2,3],[9,3,2]])
print(arr1,"\n")

#        row,column 
print(arr1[1,2])
print(arr1[0:2,2])
print(arr1[-1])
print(arr1[-1,:2])
print(arr1[:,1:3])


[[6 7 8]
 [1 2 3]
 [9 3 2]] 

3
[8 3]
[9 3 2]
[9 3]
[[7 8]
 [2 3]
 [3 2]]


<h1 style="color: DodgerBlue">2. Itreting through an Array</h1>

In [4]:
arr = np.array([[6,7,8],[1,2,3],[9,3,2]])
for row in arr:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [5]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

- <h4 style="color:SlateBlue">Using normal for loop iteration</h4>

In [6]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


- <h4 style="color:SlateBlue">For loop with flatten</h4>

In [7]:
for cell in a.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


<h2 style="color: MediumSeaGreen; text-align: center;font-weight:700">nditer()</h2>

<img src="order.png" width="200" style=" display: block;margin-left: auto;margin-right: auto;width: 50%;">

- <h4 style="color:SlateBlue">C style ordering</h4>

In [8]:
for x in np.nditer(a, order='C'):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


- <h4 style="color:SlateBlue">F style ordering</h4>

In [9]:
for x in np.nditer(a, order='F'):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


- <h4 style="color:SlateBlue">External Loop</h4>

In [10]:
for x in np.nditer(a, flags=['external_loop'],order='F'):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


- <h3 style="color:SlateBlue">Modifying array values while iterating</h3>

In [11]:
for x in np.nditer(a, op_flags=['readwrite']):
    x[...] = x * x
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

- <h3 style="color:SlateBlue">Iterate two broadcastable arrays concurrently</h3>

In [12]:
b = np.arange(3, 15, 4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [13]:
for x, y in np.nditer([a,b]):
    print (x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11


<h1 style="color:salmon">3. Stacking NumPy Arrays</h1>

In [14]:
arr1 = np.arange(6).reshape(3,2)
arr2 = np.arange(6,12).reshape(3,2)
print("arr1:\n",arr1,"\n")
print("arr2:\n",arr2)

arr1:
 [[0 1]
 [2 3]
 [4 5]] 

arr2:
 [[ 6  7]
 [ 8  9]
 [10 11]]


In [15]:
np.vstack((arr1,arr2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [16]:
np.hstack((arr1,arr2))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [17]:
arr3 = np.arange(30).reshape(2,15)
res = np.hsplit(arr3,3)
print(res[0],"\n")
print(res[1],"\n")
print(res[2],"\n")

[[ 0  1  2  3  4]
 [15 16 17 18 19]] 

[[ 5  6  7  8  9]
 [20 21 22 23 24]] 

[[10 11 12 13 14]
 [25 26 27 28 29]] 



In [18]:
res = np.vsplit(arr3,2)
print(res[0],"\n")
print(res[1],"\n")

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]] 

[[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]] 



<h1 style="color:DarkSlateBlue">4. Indexing with Boolean Arrays</h1>

In [19]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
b = arr>4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [21]:
arr[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [22]:
arr[b] =69
arr

array([[ 0,  1,  2,  3],
       [ 4, 69, 69, 69],
       [69, 69, 69, 69]])