In [1]:
import torch
print(torch.__version__)

2.7.0+cu126


In [2]:
# check if GPU & CUDA is available:

if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU :: {torch.cuda.get_device_name(0)}")
    print(f"CUDA version (runtime) :: {torch.version.cuda}")
else:
    print("⚠️ GPU not available.\nUsing CPU!")

GPU is available
Using GPU :: NVIDIA GeForce RTX 2060
CUDA version (runtime) :: 12.6


## Creating a Tensor
---

In [3]:
# using empty
a = torch.empty(2,3)
print(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [4]:
type(a)

torch.Tensor

In [5]:
torch.zeros(2,3) # returns zeros of the provided shape in the arguments

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
torch.ones(3,4) # returns ones of the provided shape in the arguments

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [7]:
torch.rand(3,3) # produces random value on each run

tensor([[0.7653, 0.4804, 0.2433],
        [0.5168, 0.1108, 0.0166],
        [0.2408, 0.4428, 0.0071]])

In [8]:
# manual_seed
torch.manual_seed(100) # seed persist the randomly generated data. 
# If another person also give the same seed they will also get the same result
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [9]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

## Tensor Shapes
---

In [11]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
x.shape

torch.Size([2, 3])

In [13]:
torch.empty_like(x)

tensor([[4710383880048,             0,             0],
        [            0,             0,             0]])

In [14]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [15]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [16]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Tensor Data Type

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


In [17]:
# find data type
x.dtype

torch.int64

In [18]:
# assign data type to a tensor during its creation
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [19]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [20]:
# using to()
x.to(torch.float32) # basically performs typecasting

tensor([[1., 2., 3.],
        [4., 5., 6.]])

<br>

## Mathematical Expressions
---

### 1. Scalar Operations

In [21]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [22]:
print(x + 2)
print(x - 2)
print(x * 3)
print(x / 3)
print((x * 100)//3)
print(((x * 100)//3)%2)
print(x**2)

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])
tensor([[-1.2882, -1.2124],
        [-1.5817, -1.0986]])
tensor([[2.1353, 2.3627],
        [1.2549, 2.7042]])
tensor([[0.2373, 0.2625],
        [0.1394, 0.3005]])
tensor([[23., 26.],
        [13., 30.]])
tensor([[1., 0.],
        [1., 0.]])
tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])


### 2. Element wise Operation

In [23]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [24]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a**b)

tensor([[1.5526, 1.7335, 0.6679],
        [1.2502, 0.9229, 1.3130]])
tensor([[ 0.4411, -0.2205, -0.2201],
        [-0.6455, -0.5661,  0.3346]])
tensor([[0.5540, 0.7391, 0.0994],
        [0.2866, 0.1328, 0.4030]])
tensor([[1.7938, 0.7743, 0.5042],
        [0.3190, 0.2397, 1.6841]])
tensor([[0.4411, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.3346]])
tensor([[0.9983, 0.7614, 0.5145],
        [0.3218, 0.2771, 0.9096]])


In [25]:
c = torch.tensor([1, -2, 3, -4])

In [26]:
# abs - Returns the absolute value of a tensor
torch.abs(c)

tensor([1, 2, 3, 4])

In [27]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [28]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

torch.round(d)

tensor([2., 2., 4., 4.])

In [29]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [30]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [31]:
# clamp
torch.clamp(d, min=2, max=69)

tensor([2.0000, 2.3000, 3.7000, 4.4000])

### 3. Reduction Operation

In [32]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [33]:
print(torch.sum(e), end="\n\n")

print(torch.sum(e, dim=0),end="\n\n") # Column-wise Opearation

print(torch.sum(e, dim=1),end="\n\n") # Row-wise Operation

tensor(24.)

tensor([ 8.,  0., 16.])

tensor([15.,  9.])



In [34]:
print(torch.mean(e),end="\n\n")
print(torch.mean(e,dim=0),end="\n\n")

tensor(4.)

tensor([4., 0., 8.])



In [35]:
torch.median(e)

tensor(0.)

In [36]:
print(torch.min(e))
print(torch.max(e))

tensor(0.)
tensor(9.)


In [37]:
torch.prod(e)

tensor(0.)

In [38]:
torch.std(e)

tensor(4.4272)

In [39]:
torch.var(e)

tensor(19.6000)

In [40]:
print(torch.argmin(e), end="\n\n")
print(torch.argmax(e), end="\n\n")

tensor(1)

tensor(5)



### 4. Matrix Operation

In [41]:
f = torch.randint(size=(2,3), low=2, high=69)
g = torch.randint(size=(3,2), low=2, high=69)

print(f,end="\n\n")
print(g)

tensor([[59, 40, 61],
        [15, 26, 52]])

tensor([[37, 10],
        [30,  3],
        [ 2, 51]])


In [42]:
torch.matmul(f, g) # matrix multiplcation

tensor([[3505, 3821],
        [1439, 2880]])

In [43]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [44]:
# transpose
print(torch.transpose(f, 0, 1))
print(torch.transpose(g, 0, 1))

tensor([[59, 15],
        [40, 26],
        [61, 52]])
tensor([[37, 30,  2],
        [10,  3, 51]])


In [45]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[5., 9., 8.],
        [9., 7., 9.],
        [2., 6., 7.]])

In [46]:
# determinant
torch.det(h)

tensor(-110.)

In [47]:
# inverse
torch.inverse(h)

tensor([[ 0.0455,  0.1364, -0.2273],
        [ 0.4091, -0.1727, -0.2455],
        [-0.3636,  0.1091,  0.4182]])

### 5. Comparison Operator 

In [48]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[7, 8, 3],
        [6, 1, 5]])
tensor([[5, 0, 4],
        [3, 8, 8]])


In [49]:
print(i<j)
print(i>j)
print(i==j)
print(i!=j)

tensor([[False, False,  True],
        [False,  True,  True]])
tensor([[ True,  True, False],
        [ True, False, False]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[True, True, True],
        [True, True, True]])


### 6. Special Funtion 

In [50]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[3., 3., 5.],
        [0., 6., 4.]])

In [51]:
print(torch.log(k),end="\n\n")
print(torch.exp(k),end="\n\n")
print(torch.sqrt(k),end="\n\n")
print(torch.sigmoid(k),end="\n\n")
print(torch.softmax(k,dim=0),end="\n\n")
print(torch.relu(k),end="\n\n")

tensor([[1.0986, 1.0986, 1.6094],
        [  -inf, 1.7918, 1.3863]])

tensor([[ 20.0855,  20.0855, 148.4132],
        [  1.0000, 403.4288,  54.5981]])

tensor([[1.7321, 1.7321, 2.2361],
        [0.0000, 2.4495, 2.0000]])

tensor([[0.9526, 0.9526, 0.9933],
        [0.5000, 0.9975, 0.9820]])

tensor([[0.9526, 0.0474, 0.7311],
        [0.0474, 0.9526, 0.2689]])

tensor([[3., 3., 5.],
        [0., 6., 4.]])



<br>

## Inplace Operations
---

In [52]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6574, 0.3451, 0.0453],
        [0.9798, 0.5548, 0.6868]])
tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])


In [53]:
m.add_(n)

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [54]:
print(m, end="\n\n")
print(n, end="\n\n")

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

tensor([[0.4920, 0.0748, 0.9605],
        [0.3271, 0.0103, 0.9516]])



In [55]:
torch.relu(m)

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [56]:
m.relu_()

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

In [57]:
m

tensor([[1.1494, 0.4199, 1.0058],
        [1.3069, 0.5650, 1.6384]])

<br>

## Copying Tensors
---

In [58]:
a = torch.rand(2,3)
a

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [59]:
b = a # Passing the actual reference of the Tensor Object

print(b)

tensor([[0.2855, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])


In [60]:
a[0][0] = 0

print(a)

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])


In [61]:
b

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

In [62]:
id(a)

2078962509024

In [63]:
id(b)

2078962509024

In [64]:
b = a.clone() # passes a copy of the Tensor

In [65]:
print(a,end="\n\n")
print(b, end="\n\n")

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])



In [66]:
a[0][0] = 10

print(a,end="\n\n")
print(b, end="\n\n")

tensor([[10.0000,  0.2324,  0.9141],
        [ 0.7668,  0.1659,  0.4393]])

tensor([[0.0000, 0.2324, 0.9141],
        [0.7668, 0.1659, 0.4393]])



In [67]:
id(a)

2078962509024

In [68]:
id(b)

2078962394416