# NumPy Quick Notes

In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,6,46,44,32,36]],np.int64)

In [3]:
myarr

array([[ 3,  6, 46, 44, 32, 36]])

In [4]:
myarr.dtype

dtype('int64')

In [5]:
print(myarr[0,1],"\n")
myarr[0,1]=45
myarr

6 



array([[ 3, 45, 46, 44, 32, 36]])

# Array Creation & Operations

- ***Conversion from other python Data Structures***

In [6]:
listarr = np.array([[1,2,3],[6,9,7],[33,44,55]])
listarr

array([[ 1,  2,  3],
       [ 6,  9,  7],
       [33, 44, 55]])

In [7]:
print(listarr.dtype)
print(listarr.shape)
print(listarr.size)

int64
(3, 3)
9


In [8]:
dict_arr = np.array({23,34,32,36,36})
print(dict_arr,"d-type=",dict_arr.dtype)

{32, 34, 36, 23} d-type= object


- ***Intrinsic Numpy Array Creation Object***

In [9]:
zeros = np.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
ones = np.ones((2,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
rng = np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

- ***Numpy Array Methods***

In [12]:
lspace = np.linspace(1,5,4)
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [13]:
emp = np.empty((2,6))
emp

array([[7.68754700e-312, 2.86558075e-322, 0.00000000e+000,
        0.00000000e+000, 1.11260619e-306, 1.61590357e+184],
       [7.73304497e-091, 1.53404729e-075, 1.26867196e-076,
        3.31184478e-033, 6.48224659e+170, 5.82471487e+257]])

In [14]:
emp_like = np.empty_like(lspace)
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [15]:
ide = np.identity(45)
print(ide,"\n")
print(ide.shape)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]] 

(45, 45)


In [16]:
arr = np.arange(99)
print(arr,"\n")
print("="*5,"Reshaped Array","="*5)
print(arr.reshape(3,33))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98] 

===== Reshaped Array =====
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56
  57 58 59 60 61 62 63 64 65]
 [66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89
  90 91 92 93 94 95 96 97 98]]


In [17]:
print(arr.ravel(),"\n")
print(arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98] 

(99,)


---

### Axis in NumPy

- ***Axis 0: Row wise Operations/ Operations in row direction***
- ***Axis 1: Column wise Operations/ Operation in column direction***

In [18]:
x = [[1,2,3],[4,5,6],[7,1,0]]
ar = np.array(x)
print(ar,"\n")

print("Row-Wise Sum: ",ar.sum(axis=0))
print("Column-Wise Sum: ",ar.sum(axis=1))

[[1 2 3]
 [4 5 6]
 [7 1 0]] 

Row-Wise Sum:  [12  8  9]
Column-Wise Sum:  [ 6 15  8]


In [19]:
print("Transpose of Matrix:\n",ar.T)

Transpose of Matrix:
 [[1 4 7]
 [2 5 1]
 [3 6 0]]


- ***arg-min & arg-max***

In [20]:
one = np.array([1,3,4,69,2,5])
print(one.argmax()) # Prints the index where is the max value
print(one.argmin()) # Prints the index where is the min value

3
0


In [21]:
one.argsort()

array([0, 4, 1, 2, 5, 3])