<h1 style='color:blue;' align='center'>KFold Cross Validation</h1>

---

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

**Logistic Regression**

In [3]:
lr = LogisticRegression(solver='liblinear')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)*100

94.81481481481482

**SVM**

In [4]:
svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)*100

52.22222222222223

**Random Forest**

In [5]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)*100

96.48148148148148

<h2 style='color:tomato'>KFold cross validation</h2>

**Basic example**

In [6]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [7]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


**Use KFold for our digits example**

In [8]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [9]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [10]:
[x * 100 for x in scores_logistic]

[89.48247078464107, 95.32554257095158, 90.98497495826378]

In [11]:
[x * 100 for x in scores_svm]

[38.06343906510851, 41.068447412353926, 51.25208681135225]

In [12]:
[x*100 for x in scores_rf]

[93.98998330550918, 94.32387312186978, 91.48580968280467]

<h2 style='color:tomato'>cross_val_score function</h2>

In [13]:
from sklearn.model_selection import cross_val_score

**Logistic regression model performance using cross_val_score**

In [14]:
cross_val_score(LogisticRegression(solver='liblinear'), digits.data, digits.target,cv=3)

array([0.89482471, 0.95325543, 0.90984975])

**svm model performance using cross_val_score**

In [15]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=3)*100

array([38.06343907, 41.06844741, 51.25208681])

**random forest performance using cross_val_score**

In [16]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3)*100

array([92.32053422, 96.32721202, 92.48747913])

***cross_val_score uses stratifield kfold by default***

<h2 style='color:tomato'>Parameter tunning using k fold cross validation</h2>

In [17]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
print(np.average(scores1))

0.868653010552452


In [18]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
print(np.average(scores2)*100)

92.98758535071381


In [19]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
print(np.average(scores3)*100)

94.54531346989447


In [20]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
print(np.average(scores4)*100)

93.98913718187461


Here we used cross_val_score to
fine tune our random forest classifier and figured that having around 40 trees in random forest gives best result. 